color0 #18120f
color1 #ffb4ab
color2 #ffb68e
color3 #e6beab
color4 #cec991
color5 #ffb68e
color6 #e6beab
color7 #ece0db
color8 #9f8d84
color9 #ffb4ab
color10 #ffb68e
color11 #e6beab
color12 #cec991
color13 #ffb68e
color14 #e6beab
color15 #ece0db

cursor                #ece0db
cursor_text_color     #18120f
background            #18120f
foreground            #ece0db
selection_foreground  #d7c2b9
selection_background  #52443c
active_border_color   #ffb68e
inactive_border_color #52443c
url_color             #ffb68e
